:identifier:
  :root: 1.2.3.4
  :extension: header_ext
:authors:
- :ids:
  - :root: 2.16.840.1.113883.3.416
    :extension: health-data-standards-gem
  :device:
    :name: popHealth2
    :model: v2.1.2
  :addresses:
  - :street:
    - MITRE Corporation
    - 732 Robertson Rd
    :city: South Elgin
    :state: IL
    :zip: '60177'
    :country: US
  :telecoms:
  - :use: WP
    :value: (847)608-7316
  :time: 2013-10-02 11:06:06.575065000 -05:00
  :organization:
    :ids:
    - :root: 2.16.840.1.113883.3.1502
      :extension: mitre-org
    :name: mitre-org
:custodian:
  :ids:
  - :root: 1.2.3.4
    :extension: custodian_ext
  :person:
    :given: Jeff
    :family: Lunt
  :organization:
    :ids:
    - :root: 1.2.3.4
      :extension: custodian_organization_ext
    :name: ''
:legal_authenticator:
  :ids:
  - :root: 1.2.3.4
    :extension: legal_authenticator_ext
  :addresses: []
  :telecoms: []
  :time: 
  :person:
    :given: hey
    :family: there
  :organization:
    :ids:
    - :root: 1.2.3.4
      :extension: legal_authenticator_org_ext
    :name: ''